services:
  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: mongodb:1.0.0
    container_name: mongodb

  catalogue:
    build: 
      context: ./catalogue
      dockerfile: Dockerfile
    image: catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb

  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    image: user:1.0.0
    container_name: user
    depends_on:
    - redis

  redis:
    image: redis:7.0
    container_name: redis

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: frontend:1.0.0
    container_name: frontend
    depends_on:
    - catalogue
    - user


networks:
  default:
    driver: bridge
    name: roboshop
    external: false